import type { MENARole, Expert, CareerInsight } from '@/types'

export const MENA_ROLES: MENARole[] = [
  {
    id: 'data-analyst-aramco',
    title: 'Data Analyst',
    company: 'Saudi Aramco',
    location: 'Dhahran',
    requiredSkills: [
      { name: 'Python', level: 7, category: 'technical' },
      { name: 'SQL', level: 8, category: 'technical' },
      { name: 'Data Visualization', level: 6, category: 'technical' },
      { name: 'Statistics', level: 6, category: 'technical' },
      { name: 'Stakeholder Management', level: 5, category: 'business' },
      { name: 'Presentation Skills', level: 5, category: 'soft' },
    ],
  },
  {
    id: 'pm-careem',
    title: 'Product Manager',
    company: 'Careem',
    location: 'Dubai',
    requiredSkills: [
      { name: 'Agile/Scrum', level: 8, category: 'business' },
      { name: 'Stakeholder Management', level: 9, category: 'business' },
      { name: 'SQL', level: 5, category: 'technical' },
      { name: 'Business Strategy', level: 7, category: 'business' },
      { name: 'Cross-Cultural Leadership', level: 7, category: 'soft' },
      { name: 'Arabic Business Communication', level: 5, category: 'soft' },
    ],
  },
  {
    id: 'cloud-eng-stc',
    title: 'Cloud Engineer',
    company: 'STC',
    location: 'Riyadh',
    requiredSkills: [
      { name: 'AWS', level: 8, category: 'technical' },
      { name: 'Linux', level: 7, category: 'technical' },
      { name: 'Networking', level: 7, category: 'technical' },
      { name: 'Terraform', level: 6, category: 'technical' },
      { name: 'Python', level: 5, category: 'technical' },
      { name: 'Agile/Scrum', level: 5, category: 'business' },
    ],
  },
  {
    id: 'aiml-neom',
    title: 'AI/ML Engineer',
    company: 'NEOM',
    location: 'NEOM',
    requiredSkills: [
      { name: 'Python', level: 9, category: 'technical' },
      { name: 'Machine Learning', level: 8, category: 'technical' },
      { name: 'Deep Learning', level: 7, category: 'technical' },
      { name: 'Cloud Architecture', level: 6, category: 'technical' },
      { name: 'Mathematics', level: 7, category: 'technical' },
      { name: 'Research Communication', level: 6, category: 'soft' },
    ],
  },
  {
    id: 'ux-noon',
    title: 'UX Designer',
    company: 'Noon',
    location: 'Dubai',
    requiredSkills: [
      { name: 'Figma', level: 9, category: 'technical' },
      { name: 'User Research', level: 8, category: 'business' },
      { name: 'Prototyping', level: 7, category: 'technical' },
      { name: 'Arabic UX Patterns', level: 6, category: 'technical' },
      { name: 'Cross-Cultural Leadership', level: 5, category: 'soft' },
    ],
  },
  {
    id: 'marketing-almarai',
    title: 'Digital Marketing Manager',
    company: 'Almarai',
    location: 'Riyadh',
    requiredSkills: [
      { name: 'SEO/SEM', level: 7, category: 'technical' },
      { name: 'Analytics', level: 7, category: 'technical' },
      { name: 'Arabic Copywriting', level: 8, category: 'soft' },
      { name: 'Business Strategy', level: 6, category: 'business' },
      { name: 'Presentation Skills', level: 6, category: 'soft' },
    ],
  },
  {
    id: 'cybersec-snb',
    title: 'Cybersecurity Analyst',
    company: 'Saudi National Bank',
    location: 'Riyadh',
    requiredSkills: [
      { name: 'Network Security', level: 8, category: 'technical' },
      { name: 'SIEM Tools', level: 7, category: 'technical' },
      { name: 'Python', level: 6, category: 'technical' },
      { name: 'Risk Management', level: 7, category: 'business' },
      { name: 'Compliance', level: 7, category: 'business' },
    ],
  },
  {
    id: 'swe-talabat',
    title: 'Software Engineer',
    company: 'Talabat',
    location: 'Kuwait City',
    requiredSkills: [
      { name: 'React', level: 8, category: 'technical' },
      { name: 'Node.js', level: 7, category: 'technical' },
      { name: 'SQL', level: 6, category: 'technical' },
      { name: 'System Design', level: 7, category: 'technical' },
      { name: 'Agile/Scrum', level: 6, category: 'business' },
    ],
  },
  {
    id: 'ba-pif',
    title: 'Business Analyst',
    company: 'PIF',
    location: 'Riyadh',
    requiredSkills: [
      { name: 'Financial Modeling', level: 8, category: 'business' },
      { name: 'Business Strategy', level: 8, category: 'business' },
      { name: 'Stakeholder Management', level: 7, category: 'business' },
      { name: 'Data Visualization', level: 6, category: 'technical' },
      { name: 'Arabic Business Communication', level: 8, category: 'soft' },
      { name: 'Presentation Skills', level: 8, category: 'soft' },
    ],
  },
  {
    id: 'fintech-stcpay',
    title: 'FinTech Developer',
    company: 'stc pay',
    location: 'Riyadh',
    requiredSkills: [
      { name: 'React Native', level: 8, category: 'technical' },
      { name: 'Node.js', level: 7, category: 'technical' },
      { name: 'API Design', level: 8, category: 'technical' },
      { name: 'Security', level: 7, category: 'technical' },
      { name: 'FinTech Regulations', level: 6, category: 'business' },
    ],
  },
]

export const EXPERT_NETWORK: Expert[] = [
  {
    id: 'fatima-rashidi',
    name: 'Fatima Al-Rashidi',
    initials: 'FA',
    title: 'Senior Data Scientist',
    company: 'Saudi Aramco',
    location: 'Dhahran',
    specialization: 'Data Science & ML in Oil & Gas',
    industries: ['Oil & Gas', 'Data Science', 'AI'],
    bio: "Led data transformation at Aramco's Digital Transformation program. Mentor for 50+ data professionals across the GCC.",
  },
  {
    id: 'omar-hassan',
    name: 'Omar Hassan',
    initials: 'OH',
    title: 'VP Product',
    company: 'Careem',
    location: 'Dubai',
    specialization: 'Product Strategy in MENA Super-Apps',
    industries: ['E-commerce', 'FinTech', 'Product Management'],
    bio: "Scaled Careem's super-app from 2 to 12 product verticals across 15 MENA markets.",
  },
  {
    id: 'layla-mahmoud',
    name: 'Layla Mahmoud',
    initials: 'LM',
    title: 'Cloud Architect',
    company: 'STC',
    location: 'Riyadh',
    specialization: 'Cloud Infrastructure & Saudization Programs',
    industries: ['Telecom', 'Cloud', 'Government'],
    bio: "Architected STC's migration to AWS and Azure serving 17M customers.",
  },
  {
    id: 'khalid-otaibi',
    name: 'Khalid Al-Otaibi',
    initials: 'KO',
    title: 'AI Research Lead',
    company: 'KACST',
    location: 'Riyadh',
    specialization: 'Applied AI Research & NEOM Technology',
    industries: ['Government', 'AI Research', 'Smart Cities'],
    bio: 'Leading AI research for Saudi Vision 2030 smart city initiatives. PhD in Machine Learning from KAUST.',
  },
  {
    id: 'nour-ibrahim',
    name: 'Nour Ibrahim',
    initials: 'NI',
    title: 'UX Lead',
    company: 'Noon',
    location: 'Cairo',
    specialization: 'Arabic UX & RTL Design Systems',
    industries: ['E-commerce', 'UX Design', 'Mobile'],
    bio: "Designed Noon's Arabic-first design system used by 10M+ shoppers.",
  },
  {
    id: 'ahmed-saleh',
    name: 'Ahmed Saleh',
    initials: 'AS',
    title: 'CISO',
    company: 'Gulf Bank',
    location: 'Kuwait City',
    specialization: 'FinTech Cybersecurity & Compliance',
    industries: ['Banking', 'FinTech', 'Cybersecurity'],
    bio: 'Built Gulf Bank cybersecurity function to ISO 27001 compliance. Advisor to Central Bank of Kuwait.',
  },
  {
    id: 'sara-ghamdi',
    name: 'Sara Al-Ghamdi',
    initials: 'SG',
    title: 'Engineering Manager',
    company: 'stc pay',
    location: 'Riyadh',
    specialization: 'FinTech Engineering & Saudi Women in Tech',
    industries: ['FinTech', 'Mobile', 'Engineering Leadership'],
    bio: "Engineering Manager at stc pay leading 25-person team building Saudi Arabia's #1 digital wallet.",
  },
  {
    id: 'youssef-karim',
    name: 'Youssef Karim',
    initials: 'YK',
    title: 'Senior Business Analyst',
    company: 'PIF',
    location: 'Riyadh',
    specialization: 'Investment Analysis & Vision 2030 Sectors',
    industries: ['Government', 'Finance', 'Strategy'],
    bio: 'Senior BA at the Public Investment Fund on Vision 2030 giga-projects. MBA from INSEAD.',
  },
]

export const CAREER_INSIGHTS: CareerInsight[] = [
  {
    stat: '78% of Data roles in KSA require Python',
    description: 'Python dominates data analytics and ML job requirements across Saudi Arabia.',
    source: 'LinkedIn Jobs Saudi Arabia Report 2024',
    relevantRoles: ['Data Analyst', 'AI/ML Engineer', 'Business Analyst'],
    location: 'Saudi Arabia',
    topics: ['python', 'data', 'programming', 'skills'],
  },
  {
    stat: 'Saudization target: 45% in banking by 2026',
    description: 'The Nitaqat program is increasing mandatory Saudi national employment quotas in finance and tech.',
    source: 'HRDF Saudi Arabia 2024',
    relevantRoles: ['Business Analyst', 'Cybersecurity Analyst', 'FinTech Developer'],
    location: 'Saudi Arabia',
    topics: ['saudization', 'nitaqat', 'banking', 'compliance', 'career'],
  },
  {
    stat: 'Vision 2030 created 127,000 net tech jobs in 2023',
    description: "Saudi Arabia's giga-projects (NEOM, Red Sea Project, Qiddiya) are driving unprecedented demand for tech talent.",
    source: 'Saudi Data & AI Authority (SDAIA) 2024',
    relevantRoles: ['AI/ML Engineer', 'Cloud Engineer', 'Software Engineer'],
    location: 'Saudi Arabia',
    topics: ['vision 2030', 'jobs', 'tech', 'growth', 'neom'],
  },
  {
    stat: 'AWS certification increases GCC salary offers by avg 23%',
    description: 'Cloud certifications are among the highest-ROI credentials for tech professionals across the GCC.',
    source: 'Bayt.com MENA Salary Survey 2024',
    relevantRoles: ['Cloud Engineer', 'AI/ML Engineer', 'Software Engineer'],
    location: 'GCC',
    topics: ['aws', 'cloud', 'certification', 'salary', 'skills'],
  },
  {
    stat: 'Arabic-English bilingual PMs earn 18% more in Dubai',
    description: "Bilingual product managers command a significant premium in Dubai's diverse tech market.",
    source: 'Naukrigulf Salary Report 2024',
    relevantRoles: ['Product Manager', 'Digital Marketing Manager'],
    location: 'UAE',
    topics: ['arabic', 'bilingual', 'product', 'dubai', 'salary'],
  },
  {
    stat: 'Emiratization: 10% of private sector roles by 2026',
    description: "UAE's Nafis program mandates increasing Emirati employment quotas in private sector companies.",
    source: 'UAE Ministry of Human Resources 2024',
    relevantRoles: ['Software Engineer', 'Product Manager', 'Business Analyst'],
    location: 'UAE',
    topics: ['emiratization', 'nafis', 'uae', 'career', 'compliance'],
  },
  {
    stat: 'FinTech roles in KSA grew 340% from 2020-2024',
    description: "Saudi Arabia's SAMA regulatory sandbox and the rise of digital payments has made FinTech one of the fastest-growing career sectors.",
    source: 'SAMA FinTech Report 2024',
    relevantRoles: ['FinTech Developer', 'Cybersecurity Analyst', 'Business Analyst'],
    location: 'Saudi Arabia',
    topics: ['fintech', 'growth', 'payments', 'saudi', 'banking'],
  },
]
